create table if not exists public.app_state (
  id text primary key,
  user_id uuid,
  data jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.app_state
add column if not exists user_id uuid;

alter table public.app_state enable row level security;

drop policy if exists "app_state_select_anon" on public.app_state;
drop policy if exists "app_state_insert_anon" on public.app_state;
drop policy if exists "app_state_update_anon" on public.app_state;
drop policy if exists "app_state_select_own" on public.app_state;
drop policy if exists "app_state_insert_own" on public.app_state;
drop policy if exists "app_state_update_own" on public.app_state;
drop policy if exists "app_state_delete_own" on public.app_state;

create policy "app_state_select_own"
on public.app_state for select
to authenticated
using (user_id = auth.uid());

create policy "app_state_insert_own"
on public.app_state for insert
to authenticated
with check (user_id = auth.uid());

create policy "app_state_update_own"
on public.app_state for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "app_state_delete_own"
on public.app_state for delete
to authenticated
using (user_id = auth.uid());

-- 增量同步事件：客户端先写入本地 outbox，再在联网后追加事件。
create table if not exists public.app_state_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  device_id text not null,
  changed_at timestamptz not null default now(),
  domains text[] not null default '{}',
  state_version text not null
);

alter table public.app_state_events enable row level security;
drop policy if exists "app_state_events_own" on public.app_state_events;
create policy "app_state_events_own"
on public.app_state_events for all
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create index if not exists app_state_events_user_time_idx
on public.app_state_events (user_id, changed_at desc);
